import type { Team, Match, News, Sponsor, SocioTier } from "@/types";

export const teams: Team[] = [
  {
    id: "1",
    name: "Veteranos",
    slug: "veteranos",
    category: "Veteranos",
    categoryTier: "senior",
    photo: "/images/teams/veteranos.jpg",
    coach: "Paco Martínez",
    players: [
      { id: "v1", name: "Josep Ferrer", position: "Portero", number: 1 },
      { id: "v2", name: "Toni Blasco", position: "Defensa", number: 4 },
      { id: "v3", name: "Manolo Català", position: "Defensa", number: 5 },
      { id: "v4", name: "Rafa Soler", position: "Centrocampista", number: 8 },
      { id: "v5", name: "Miquel Ortiz", position: "Centrocampista", number: 10 },
      { id: "v6", name: "Carlos Ibáñez", position: "Delantero", number: 9 },
      { id: "v7", name: "Vicent Pérez", position: "Delantero", number: 11 },
    ],
  },
  {
    id: "2",
    name: "Amateur A Masculino",
    slug: "amateur-a-masculino",
    category: "Amateur A",
    categoryTier: "senior",
    photo: "/images/teams/amateur-a-masculino.jpg",
    coach: "Sergio Navarro",
    players: [
      { id: "am1", name: "Adrià Molina", position: "Portero", number: 1 },
      { id: "am2", name: "Pablo Vidal", position: "Defensa", number: 2 },
      { id: "am3", name: "Jordi Espinosa", position: "Defensa", number: 3 },
      { id: "am4", name: "Lluís Carbonell", position: "Defensa", number: 4 },
      { id: "am5", name: "Xavi Domínguez", position: "Centrocampista", number: 6 },
      { id: "am6", name: "Dani Sánchez", position: "Centrocampista", number: 8 },
      { id: "am7", name: "Marc Ribas", position: "Delantero", number: 9 },
      { id: "am8", name: "Álvaro Climent", position: "Delantero", number: 11 },
    ],
  },
  {
    id: "3",
    name: "Amateur Femenino",
    slug: "amateur-femenino",
    category: "Amateur Femenino",
    categoryTier: "senior",
    photo: "/images/teams/amateur-femenino.jpg",
    coach: "Laura Gimeno",
    players: [
      { id: "af1", name: "Cristina Fuster", position: "Portera", number: 1 },
      { id: "af2", name: "Neus Almenar", position: "Defensa", number: 2 },
      { id: "af3", name: "Paula Vilar", position: "Defensa", number: 5 },
      { id: "af4", name: "Sara Montagud", position: "Centrocampista", number: 7 },
      { id: "af5", name: "Marina Llorens", position: "Centrocampista", number: 10 },
      { id: "af6", name: "Cèlia Bosch", position: "Delantera", number: 9 },
    ],
  },
  {
    id: "4",
    name: "Amateur B Masculino",
    slug: "amateur-b-masculino",
    category: "Amateur B",
    categoryTier: "senior",
    photo: "/images/teams/amateur-b-masculino.jpg",
    coach: "Enric Ballester",
    players: [
      { id: "ab1", name: "Quique Mora", position: "Portero", number: 1 },
      { id: "ab2", name: "Iván Mestre", position: "Defensa", number: 3 },
      { id: "ab3", name: "Rubén Aliaga", position: "Defensa", number: 4 },
      { id: "ab4", name: "Toni Palau", position: "Centrocampista", number: 6 },
      { id: "ab5", name: "Gerard Muñoz", position: "Centrocampista", number: 8 },
      { id: "ab6", name: "Óscar Ferrandis", position: "Delantero", number: 9 },
      { id: "ab7", name: "Sergio Garrido", position: "Delantero", number: 11 },
    ],
  },
  {
    id: "5",
    name: "Juvenil",
    slug: "juvenil",
    category: "Juvenil",
    categoryTier: "youth-senior",
    photo: "/images/teams/juvenil.jpg",
    coach: "Ramón Esteban",
    players: [
      { id: "j1", name: "Pau Hernández", position: "Portero", number: 1 },
      { id: "j2", name: "Álex Gómez", position: "Defensa", number: 2 },
      { id: "j3", name: "Bruno Navarro", position: "Defensa", number: 5 },
      { id: "j4", name: "Nil Celades", position: "Centrocampista", number: 8 },
      { id: "j5", name: "Diego Puchades", position: "Centrocampista", number: 10 },
      { id: "j6", name: "Biel Calatayud", position: "Delantero", number: 9 },
    ],
  },
  {
    id: "6",
    name: "Alevín A",
    slug: "alevin-a",
    category: "Alevín A",
    categoryTier: "youth-junior",
    photo: "/images/teams/alevin-a.jpg",
    coach: "Miquel Àngel Torres",
    players: [
      { id: "aa1", name: "Jan Llopis", position: "Portero", number: 1 },
      { id: "aa2", name: "Roc Miralles", position: "Defensa", number: 4 },
      { id: "aa3", name: "Cesc Puig", position: "Centrocampista", number: 8 },
      { id: "aa4", name: "Pol Alcácer", position: "Delantero", number: 9 },
      { id: "aa5", name: "Unai Bataller", position: "Delantero", number: 11 },
    ],
  },
  {
    id: "7",
    name: "Alevín B",
    slug: "alevin-b",
    category: "Alevín B",
    categoryTier: "youth-junior",
    photo: "/images/teams/alevin-b.jpg",
    coach: "Begoña Martí",
    players: [
      { id: "ab1b", name: "Arnau Sempere", position: "Portero", number: 1 },
      { id: "ab2b", name: "Leo Dasi", position: "Defensa", number: 3 },
      { id: "ab3b", name: "Nico Rodrigo", position: "Centrocampista", number: 7 },
      { id: "ab4b", name: "Mateu Torro", position: "Delantero", number: 9 },
    ],
  },
  {
    id: "8",
    name: "Benjamín A",
    slug: "benjamin-a",
    category: "Benjamín A",
    categoryTier: "youth-junior",
    photo: "/images/teams/benjamin-a.jpg",
    coach: "Joan Carles Valls",
    players: [
      { id: "ba1", name: "Teo Calabuig", position: "Portero", number: 1 },
      { id: "ba2", name: "Gael Ferrer", position: "Defensa", number: 2 },
      { id: "ba3", name: "Hugo Beltran", position: "Centrocampista", number: 6 },
      { id: "ba4", name: "Nil Comes", position: "Delantero", number: 9 },
    ],
  },
  {
    id: "9",
    name: "Benjamín B",
    slug: "benjamin-b",
    category: "Benjamín B",
    categoryTier: "youth-junior",
    photo: "/images/teams/benjamin-b.jpg",
    coach: "Amparo Ribes",
    players: [
      { id: "bb1", name: "Oriol Moner", position: "Portero", number: 1 },
      { id: "bb2", name: "Santi Cano", position: "Defensa", number: 4 },
      { id: "bb3", name: "Álex Clausell", position: "Centrocampista", number: 8 },
      { id: "bb4", name: "Jaume Esteve", position: "Delantero", number: 10 },
    ],
  },
  {
    id: "10",
    name: "Prebenjamín",
    slug: "prebenjamin",
    category: "Prebenjamín",
    categoryTier: "youth-junior",
    photo: "/images/teams/prebenjamin.jpg",
    coach: "Néstor Albelda",
    players: [
      { id: "pb1", name: "Leo Pedrós", position: "Portero", number: 1 },
      { id: "pb2", name: "Pau Silvestre", position: "Defensa", number: 3 },
      { id: "pb3", name: "Iker Meseguer", position: "Centrocampista", number: 7 },
      { id: "pb4", name: "Max Lluch", position: "Delantero", number: 9 },
    ],
  },
  {
    id: "11",
    name: "Querubín",
    slug: "querubin",
    category: "Querubín",
    categoryTier: "youth-junior",
    photo: "/images/teams/querubin.jpg",
    coach: "Sandra Pérez",
    players: [
      { id: "q1", name: "Berta Mas", position: "Portera", number: 1 },
      { id: "q2", name: "Laia Faus", position: "Defensa", number: 4 },
      { id: "q3", name: "Martina Palau", position: "Centrocampista", number: 7 },
      { id: "q4", name: "Sofía Colom", position: "Delantera", number: 9 },
    ],
  },
];

export const matches: Match[] = [
  {
    id: "m1",
    teamId: "2",
    rival: "CF Campanar",
    date: "2025-01-18",
    time: "17:00",
    location: "Camp Municipal de Benimaclet",
    isHome: true,
    result: "2-1",
  },
  {
    id: "m2",
    teamId: "2",
    rival: "Valencia CF Mestalla B",
    date: "2025-01-25",
    time: "11:00",
    location: "Camp de la Petxina",
    isHome: false,
    result: "0-3",
  },
  {
    id: "m3",
    teamId: "2",
    rival: "Paterna CF",
    date: "2025-02-01",
    time: "17:00",
    location: "Camp Municipal de Benimaclet",
    isHome: true,
    result: "1-1",
  },
  {
    id: "m4",
    teamId: "2",
    rival: "CD Alboraya",
    date: "2025-02-15",
    time: "17:00",
    location: "Camp Municipal de Benimaclet",
    isHome: true,
  },
  {
    id: "m5",
    teamId: "2",
    rival: "SD Burjassot",
    date: "2025-02-22",
    time: "11:30",
    location: "Camp Municipal de Burjassot",
    isHome: false,
  },
  {
    id: "m6",
    teamId: "2",
    rival: "Torrent CF",
    date: "2025-03-01",
    time: "17:00",
    location: "Camp Municipal de Benimaclet",
    isHome: true,
  },
];

export const news: News[] = [
  {
    id: "n1",
    title: "Campus de Nadal",
    slug: "campus-de-nadal",
    date: "2025-12-16",
    category: "Escola / Esdeveniments",
    excerpt:
      "Apunta't al Campus de Nadal del Sporting de Benimaclet. Dies de futbol, diversió i barri per als més menuts. Contacta amb nosaltres per a més informació.",
    image: "https://picsum.photos/seed/campus-nadal-sporting/800/450",
    content:
      "El Sporting de Benimaclet organitza un Campus de Nadal per als xiquets i xiquetes del barri. Dies de futbol, convivència i moltes ganes de gaudir de l'esport. Si vols apuntar al teu fill o filla, contacta amb nosaltres a través del correu o les xarxes socials. Places limitades.",
  },
  {
    id: "n2",
    title: "El temporal deixa el camp impracticable",
    slug: "temporal-camp-impracticable",
    date: "2025-12-16",
    category: "Actualitat / Última hora",
    excerpt:
      "Les pluges registrades en les últimes hores han provocat l'acumulació de fang al camp de futbol, deixant-lo en condicions no adequades per a la pràctica esportiva.",
    image: "/images/news/camp-inundat.jpg",
    content:
      "Les pluges registrades en les últimes hores han provocat l'acumulació de fang al camp de futbol, deixant-lo en condicions no adequades per a la pràctica esportiva. Per aquest motiu, els entrenaments i partits previstos queden suspesos fins que el terreny de joc recupere les condicions òptimes. Des del club agraïm la comprensió de totes les famílies i us mantindrem informats a través de les nostres xarxes socials.",
  },
  {
    id: "n3",
    title: "Campanya d'Abonaments 25-26",
    slug: "campanya-abonaments-25-26",
    date: "2025-09-15",
    category: "Actualitat / Club",
    excerpt:
      "Portem 35 anys deixant la nostra empremta, ajuda'ns a continuar fent-ho. El Sporting Benimaclet naix i creix al barri, amb la idea d'estar més a prop que mai.",
    image: "https://picsum.photos/seed/abonaments-sporting/800/450",
    content:
      "Portem 35 anys deixant la nostra empremta al barri de Benimaclet. Ara et demanem que ens ajudes a continuar. La Campanya d'Abonaments 25-26 ja és oberta: fes-te soci i forma part d'una comunitat de més de 300 persones que creuen en el futbol popular. Quatre modalitats des de 20€/any.",
  },
  {
    id: "n4",
    title: "L'Sporting Amateur Femení ho ha tornat a fer",
    slug: "amateur-femeni-victoria-atletico-cabanyal",
    date: "2025-04-08",
    category: "Actualitat / Resultats",
    excerpt:
      "Victòria de 4-3 davant el líder Atlètico Cabanyal en un partit amb un tancament digne de pel·lícula. Eva va brillar amb un doblet i Laura va sumar un gol clau.",
    image: "https://picsum.photos/seed/femeni-victoria-cabanyal/800/450",
    content:
      "L'Sporting Amateur Femení va aconseguir una victòria històrica davant l'Atlètico Cabanyal, líder de la competició, per 4-3 en un matx d'infart. Eva va brillar amb un doblet espectacular, Laura va sumar un gol clau i l'equip va demostrar el seu caràcter fins al xiulet final. Una victòria que ha fet vibrar tot el barri.",
  },
  {
    id: "n5",
    title: "André Almeida tria el camp del Sporting per anunciar el seu fitxatge",
    slug: "andre-almeida-sporting-benimaclet",
    date: "2025-03-28",
    category: "Actualitat / Esdeveniments",
    excerpt:
      "El camp del Sporting Benimaclet CF sol ser un lloc atractiu per a l'amant del futbol per diferents raons, però la principal és la seua essència de barri.",
    image: "https://picsum.photos/seed/almeida-sporting/800/450",
    content:
      "El camp del Sporting Benimaclet CF va ser escollit per André Almeida per a anunciar el seu fitxatge per All Iron Sports. El jugador va destacar l'essència del club i la seua connexió amb el barri com a motius per a triar aquest espai tan especial. Un reconeixement més a la identitat única del Sporting.",
  },
  {
    id: "n6",
    title: "El Sporting Benimaclet rescata 500 mascotes",
    slug: "sporting-rescata-500-mascotes",
    date: "2025-03-26",
    category: "Actualitat / Comunitat",
    excerpt:
      "El club de categoria regional mobilitza la seua massa social i veïns per a habilitar el seu camp, l'últim de terra de la província de València, com a campament per a animals.",
    image: "https://picsum.photos/seed/mascotes-sporting/800/450",
    content:
      "El Sporting de Benimaclet va mobilitzar tota la seua comunitat per a habilitar el camp de Les Fonts com a refugi d'emergència per a mascotes durant la crisi. Més de 500 animals van ser acollits gràcies a l'esforç dels socis, famílies i veïns del barri. Una mostra més de que no som un club, som un barri.",
  },
  {
    id: "n7",
    title: "Escola de futbol base temporada 25/26",
    slug: "escola-futbol-base-25-26",
    date: "2025-04-01",
    category: "Escola / Club",
    excerpt:
      "Des del Sporting de Benimaclet estem treballant per a tornar a portar el futbol base al nostre barri. Volem reprendre l'Escola de futbol a Benimaclet.",
    image: "https://picsum.photos/seed/escola-base-sporting/800/450",
    content:
      "Des del Sporting de Benimaclet estem treballant per a tornar a portar el futbol base al nostre barri. Volem reprendre l'Escola de futbol a Benimaclet i estem buscant xiquets i xiquetes que vulguen formar part d'aquest projecte. Si el teu fill o filla té entre 4 i 12 anys i vol aprendre a jugar a futbol en un ambient familiar i de barri, posa't en contacte amb nosaltres.",
  },
  {
    id: "n8",
    title: "La nostra història",
    slug: "la-nostra-historia",
    date: "2025-04-01",
    category: "Blog / Club",
    excerpt:
      "Encara que poguera semblar que és només un equip més de futbol base, el Sporting Benimaclet compta darrere seu amb una història profundament arrelada al seu lloc.",
    image: "https://picsum.photos/seed/historia-sporting/800/450",
    content:
      "Encara que poguera semblar que és només un equip més de futbol base com qualsevol altre, el Sporting Benimaclet compta darrere seu amb una història profundament arrelada al seu lloc i temps de naixement. El Sporting és fill de les reivindicacions veïnals, de les lluites del Trenet i de l'energia del barri de Benimaclet.",
  },
];

export const sponsors: Sponsor[] = [
  { id: "s01", name: "Ultramarinos Javi", url: "#", description: "Alimentació de confiança", logo: "/images/sponsors/Ultramarinos_Javi.png" },
  { id: "s02", name: "Supan", url: "https://homosupan.es", description: "Forn artesà", logo: "/images/sponsors/Supan.png" },
  { id: "s03", name: "Pulso Pub", url: "#", description: "Feel The Music", logo: "/images/sponsors/Pulso_Pub.png" },
  { id: "s04", name: "Planeta Azul", url: "#", description: "Bar-Restaurante", logo: "/images/sponsors/Planeta_Azul.png" },
  { id: "s05", name: "Partisano", url: "#", description: "Bar de barri", logo: "/images/sponsors/Partisano.png" },
  { id: "s06", name: "On Air", url: "#", description: "Espai de oci i cultura", logo: "/images/sponsors/On_Air.png" },
  { id: "s07", name: "London Bar", url: "#", description: "Est. 2010", logo: "/images/sponsors/London.png" },
  { id: "s08", name: "L'Amagatall", url: "#", description: "Gastro Bar", logo: "/images/sponsors/LAmagatall_Gastro_Bar.png" },
  { id: "s09", name: "Goatxa", url: "#", description: "Since 2006 · Valencia", logo: "/images/sponsors/Goatxa.png" },
  { id: "s10", name: "Fonclima Martínez", url: "#", description: "Climatització S.L.", logo: "/images/sponsors/Fonclima_Martinez.png" },
  { id: "s11", name: "Bar Dyver", url: "#", description: "Bar de barri", logo: "/images/sponsors/Bar_Dyver.png" },
  { id: "s12", name: "Clandestí", url: "#", description: "Cocktail & Tapes", logo: "/images/sponsors/Clandesti.png" },
  { id: "s13", name: "Terra", url: "#", description: "Centre Social Bar", logo: "/images/sponsors/Terra.png" },
  { id: "s14", name: "CamiSolar", url: "#", description: "Energia Fotovoltaica", logo: "/images/sponsors/CamiSolar.png" },
  { id: "s15", name: "Calicopia", url: "#", description: "Reprografia", logo: "/images/sponsors/Calicopia.png" },
  { id: "s16", name: "Bogar Bar", url: "#", description: "Bar de barri", logo: "/images/sponsors/Bogar_Bar.png" },
  { id: "s17", name: "Ambra", url: "#", description: "Poble-Bar", logo: "/images/sponsors/Ambra.png" },
  { id: "s18", name: "Miquel Simon", url: "#", description: "Fisioterapia", logo: "/images/sponsors/Miquel_Simon_Fisioterapia.png" },
  { id: "s19", name: "Carmel@s", url: "#", description: "Panadería · Pastisseria", logo: "/images/sponsors/Carmelas.png" },
  { id: "s20", name: "Clínicas Dental Fornas", url: "#", description: "Creamos Sonrisas", logo: "/images/sponsors/Clinicas_Dental_Fornas.png" },
  { id: "s21", name: "Aprendiz", url: "#", description: "Espai creatiu", logo: "/images/sponsors/Aprendiz.png" },
  { id: "s22", name: "La Légur", url: "#", description: "Vinos y Jamones", logo: "/images/sponsors/La_Le_Gur.png" },
  { id: "s23", name: "Cien Volando", url: "#", description: "Bar & Restaurante", logo: "/images/sponsors/Cien_Volando.png" },
  { id: "s24", name: "La Gramola", url: "#", description: "Cocktail Bar", logo: "/images/sponsors/La_Gramola.png" },
  { id: "s25", name: "Bodega Alegre", url: "#", description: "Vins i destil·lats", logo: "/images/sponsors/Bodega_Alegre.png" },
  { id: "s26", name: "El Tramvia", url: "#", description: "Café + Bar · Benimaclet", logo: "/images/sponsors/El_Tramvia.png" },
  { id: "s27", name: "Torii Bar", url: "#", description: "Bar de barri", logo: "/images/sponsors/Torii_Bar.png" },
];

export const socioTiers: SocioTier[] = [
  {
    id: "estandar",
    name: "Estándar",
    price: 25,
    benefits: [
      "Carnet de socio",
      "Descuentos en la cantina",
      "Voz y voto en la asamblea",
    ],
  },
  {
    id: "reducida",
    name: "Reducida",
    price: 20,
    benefits: [
      "Carnet de socio",
      "Descuentos en la cantina",
      "Voz y voto en la asamblea",
    ],
  },
  {
    id: "oro",
    name: "Oro",
    price: 50,
    benefits: [
      "Todo lo de Estándar",
      "Camiseta oficial del club",
      "Acceso preferente a eventos",
      "Mención en la web",
    ],
  },
  {
    id: "platino",
    name: "Platino",
    price: 100,
    benefits: [
      "Todo lo de Oro",
      "Camiseta y equipación completa",
      "Entrada a partidos de gala",
      "Reunión anual con la directiva",
      "Tu nombre en el estadio",
    ],
  },
];
